/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conexion.ConexionSQL;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.WindowConstants;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jamt_
 */
public class ccReporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form ccModos
     */
    public ccReporte() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
    }

    void reporteManual(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoCajeroAutomaticoAdmin\\ProyectoFinal\\src\\Vista\\ReporteManual.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte manual: " + e);
        }
    }
    
    void reporteAuto(){
        String archivo = "C:\\Users\\jamt_\\Documents\\NetBeansProjects\\Pro\\ProyectoCajeroAutomaticoAdmin\\ProyectoFinal\\src\\Vista\\ReporteAuto.jasper";
        JasperReport jr;
        
        try {
            jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            
            JasperPrint jp = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer jv = new JasperViewer(jp,false);
            jv.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            jv.setVisible(true);
        } catch (Exception e) {
            System.out.println("Error al visualizar reporte auto: " + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManual = new LIB.FSButtonMD();
        btnAuto = new LIB.FSButtonMD();

        setClosable(true);
        setResizable(true);
        setTitle("Reportes");
        setMaximumSize(new java.awt.Dimension(649, 464));
        setMinimumSize(new java.awt.Dimension(649, 464));

        btnManual.setBackground(new java.awt.Color(255, 102, 0));
        btnManual.setText("Manual");
        btnManual.setColorNormal(new java.awt.Color(255, 102, 0));
        btnManual.setColorPressed(new java.awt.Color(255, 102, 0));
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAuto.setText("Automatico");
        btnAuto.setColorNormal(new java.awt.Color(255, 102, 0));
        btnAuto.setColorPressed(new java.awt.Color(255, 102, 0));
        btnAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(693, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(613, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
        // TODO add your handling code here:
        reporteManual();
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoActionPerformed
        // TODO add your handling code here:
        reporteAuto();
    }//GEN-LAST:event_btnAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnAuto;
    private LIB.FSButtonMD btnManual;
    // End of variables declaration//GEN-END:variables
Conexion.ConexionSQL cc = new ConexionSQL();
Connection cn= ConexionSQL.conexionn();
}
